repos:
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
      [
        "--fast", # Match micropython black configuration
        "--line-length=99", # Match micropython black configuration
      ]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args:
      [
        "--max-line-length=99", # Match micropython black configuration
      ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.960"
  hooks:
  - id: mypy
- repo: https://github.com/pycqa/pylint
  rev: v2.11.1
  hooks:
  - id: pylint
    args:
      [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--rcfile=pylintrc", # Link to your config file
      ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args:
      [
        "--check",
        "--diff",
        "--profile black", # Compatibility with black
        "--thirdparty upible uasyncio gc microdot_asyncio",
      ]
